name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Verify Java version
        run: java -version

      - name: Display Maven version
        run: mvn -v

      - name: Show Environment Variables
        run: printenv

      - name: Display settings.xml
        run: cat $GITHUB_WORKSPACE/settings.xml

      - name: Build with Maven (Debug Mode)
        run: mvn -B package --file pom.xml -X

      - name: Publish to GitHub Packages Apache Maven (Debug Mode)
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-logs
          path: |
            target/surefire-reports
            target/*.log
